Vagrant::Config.run do |config|

  config.vm.box = "ubuntu-precise-32"
  config.vm.boot_mode = :gui
  config.vm.share_folder("v-root", "/vagrant", ".", :nfs => true)
  config.vm.network :hostonly, "10.0.73.57"

end

